### ISSUE TITLE
MTKObserver should removeObserver in dealloc

### ISSUE THREAD

**Issue by yanjunz** [iMartinKiss/Block-KVO#35]
As a associated object, `dealloc()` of MTKObserver is a excellent place to removeObserver to target. That also make MTKObserver self managed, and there is no need to call removeAllObservations outside.

**Comment by iMartinKiss** [comment]
Yes, that would be great, but I remember I tried doing exactly this. The problem was, I think, that the KVO observances were checked _before_ associated objects were released, which caused error logs to be printed to the console.

Maybe they changed deallocation implementation and it may work correctly now. Could you try it, please? If it works, open a Pull Request. It would be a great improvement.

Thanks.

**Comment by yanjunz** [comment]
Work for me. I have created a pull request, please check it.

**Comment by iMartinKiss** [comment]
Doesn’t work for me. Try adding these two lines to App Delegate in the Example app:

```objc
[self.property observeProperty:@"title" withBlock:^(id example, id old, id new) {}];
self.property = nil;
```

The first line will create an observer and the second will deallocate the Example object, which should remove observers. In my case, it crashed before `-dealloc` of `MTKObserver` was called.

**Comment by yanjunz** [comment]
since MTKObserver is element of a array which is a association object of target, MTKObserver's `dealloc` will delay to call until next runloop after target is dealloced. So I use deallocBlockExecutor as a helper to notify the related MTKObservers to detach ASAP.
I submit a another pull request.  Please review it.

**Comment by iMartinKiss** [comment]
Done. It needed swizzling `-dealloc`, but I already has the implementation in [another project](https://github.com/iMartinKiss/Objective-Chain).
